workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1 # Specify the instance type, example: mac_mini_m1

    environment:
      groups:
        - default # Example group, add your API tokens here TESTAPPIO_API_TOKEN and TESTAPPIO_APP_ID
    
    # BUILD AND UPLOAD
    scripts: 
      - name: Build and upload to TestApp.io
        script: |
          bundle install
          bundle exec fastlane android beta --verbose
